version: '3'
services:
  node:
    image: aateamapi-prod:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    container_name: aateamapi
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    working_dir: /var/www/app
    restart: always
    command: node -r dotenv/config src/index.js
    expose:
      - 4000
      - 80
    network_mode: webproxy
networks:
  default:
    external:
      name: webproxy
