version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     NODE_ENV: development
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - .:/var/www/application
      - /var/www/application/node_modules
    container_name: aateam-api
