version: "3"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgresdb_data:/var/lib/postgresql/data-teams
    networks:
      - superalgos_net

  minio:
    image: minio/minio:RELEASE.2019-07-05T21-20-21Z
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - superalgos_net

  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: prisma_secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    volumes:
      - postgresdb_data:/data/db
    networks:
      - superalgos_net
    depends_on:
      - postgres

  teams-deploy:
    image: superalgos/teams-prisma:0.1.0
    restart: "no"
    env_file: ./env/teams-prisma.env
    command: sh -c './wait-for prisma:4466 -- prisma deploy'
    networks:
      - superalgos_net
    depends_on:
      - prisma

  teams-api:
    image: superalgos/teams-api:0.1.0
    restart: always
    env_file: ./env/teams-api.env
    command: sh -c './wait-for prisma:4466 -- node .'
    networks:
      - superalgos_net
    depends_on:
      - teams-deploy

  mongo:
    image: mongo:4.0.9
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - superalgos_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - superalgos_net
    depends_on:
      - mongo

  saweb-api:
    image: superalgos/saweb-api:0.1.0
    restart: always
    env_file: ./env/saweb-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  logs-api:
    image: superalgos/logs-api:0.1.0
    restart: always
    env_file: ./env/logs-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  clones-api:
    image: superalgos/clones-api:0.1.0
    restart: always
    env_file: ./env/clones-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  cockpit-api:
    image: superalgos/cockpit-api:0.1.0
    restart: always
    env_file: ./env/cockpit-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  strategizer-api:
    image: superalgos/strategizer-api:0.1.0
    restart: always
    env_file: ./env/strategizer-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  events-api:
    image: superalgos/events-api:0.1.0
    restart: always
    env_file: ./env/events-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  users-api:
    image: superalgos/users-api:0.1.0
    restart: always
    env_file: ./env/users-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  keyvault-api:
    image: superalgos/keyvault-api:0.1.0
    restart: always
    env_file: ./env/keyvault-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - mongo-express

  notifications-api:
    image: superalgos/notifications-api:0.1.0
    restart: always
    env_file: ./env/notifications-api.env
    command: node .
    networks:
      - superalgos_net
    depends_on:
      - prisma

  master-app:
    image: superalgos/master-app:0.1.0
    restart: always
    env_file: ./env/master-app.env
    command: ["nginx"]
    ports:
      - "3100:3100"
    networks:
      - superalgos_net

  master-app-api:
    image: superalgos/master-app-api:0.1.0
    restart: always
    env_file: ./env/master-app-api.env
    command: sh -c './wait-for users-api:4000 -- ./wait-for teams-api:4001 -- ./wait-for keyvault-api:4002 -- ./wait-for clones-api:4003 -- ./wait-for saweb-api:4004 -- ./wait-for events-api:4005 -- ./wait-for notifications-api:4006 -- ./wait-for logs-api:4007 -- ./wait-for strategizer-api:4008 -- ./wait-for cockpit-api:4009 --  node .'
    ports:
      - "4100:4100"
    networks:
      - superalgos_net

  aaweb:
    image: superalgos/aaweb:0.1.0
    restart: always
    env_file: ./env/aaweb.env
    command: node server
    ports:
      - "4101:4101"
    networks:
      - superalgos_net

  kubernetes:
    image: qoomon/docker-host:2.2.0
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - superalgos_net

networks:
  superalgos_net:

volumes:
  mongodb_data:
  postgresdb_data:
