version: '3'
services:
  node:
    image: masterapp-client-dev:v1
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        APP_PATH: /var/www
    environment:
      - NODE_ENV=production
      - APP_PATH=/var/www
      - PROD_GRAPHQL=https://platform-api-dev.advancedalgos.net/graphql
      - VIRTUAL_HOST=platform-dev.advancedalgos.net
      - LETSENCRYPT_HOST=platform-dev.advancedalgos.net
      - LETSENCRYPT_EMAIL=ssl-certificates@advancedalgos.org
      - VIRTUAL_PORT=3100
    container_name: masterapp-client-dev
    tty: true
    stdin_open: true
    working_dir: ${APP_PATH}
    command: ['nginx']
    restart: always
    expose:
      - 3100
    network_mode: webproxy
networks:
  default:
    external:
      name: webproxy
