projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev1:
          url: http://0.0.0.0:4000/graphql

  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
